### ISSUE TITLE
Uploading code fails: `No such file or directory: 'udisksctl'`

### ISSUE THREAD

**Issue by SeongGino** [flathub/cc.arduino.IDE2#68]
Title. udisksctl is already installed on the host machine. Flatpak has been given permissions for reading all system libraries and files. Arch Linux.

**Comment by joshuag1000** [comment]
Would you be able to provide some more information?
What board are you trying to upload code to?

**Comment by SeongGino** [comment]
I'm uploading primarily to RP2040 boards, using Earle Philhower's RP2040 core for Arduino IDE.

I know this should work on the host natively, as I'm using native Arduino IDE 1.8.x/2.2.1 from the repos/AUR and it has no such issue.

**Comment by thesquaregroot** [comment]
I'm experiencing the same issue, also attempting to use Earle Philhower's RP2040 core for Arduino IDE.  I'm on Pop!_OS 22.04 LTS.

**Comment by joshuag1000** [comment]
Apologies for the late response. 
Have you tried the following steps on the libraries installation guide? 
https://github.com/earlephilhower/arduino-pico#linux-specific-notes

**Comment by joshuag1000** [comment]
I'm going to close this issue for now as the issue seems to be resolved even if the logs are showing an error from the library. 
If there are any more issues with this library I'd recommend reaching out to the library author and mentioning it to them as they appear to be supporting the flathub release. I'll add --system-talk-name=org.freedesktop.UDisks2 to the manifest as that allows the app to communicate with the systems UDisk2 install but its not something I can (or should) include with this package.
